name: flutter_course
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #state management
  scoped_model: ^1.1.0
  http: ^0.12.2
  shared_preferences: ^0.5.12+4
  rxdart: ^0.25.0
  #map_view:
  lee_map_view: ^2.0.0
  location: ^3.1.0


  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
analyzer:
  strong-mode: true
  language:
    enableSuperMixins: true

flutter:

  uses-material-design: true

  assets:
    - assets/

  fonts:
   - family: Lato
     fonts:
       - asset: assets/fonts/Lato-Regular.ttf
         weight: 700